on: [workflow_dispatch]

name: AzureLogin_localaction
env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v2
      
    - uses: ./.github/actions/templates/login_actions/
