on: [workflow_dispatch]

name: AzureLogin_localaction

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v2
      
    - uses: ./.github/actions/templates/login_actions/
