on: [workflow_dispatch]

name: AzureLogin_Self_Hosted

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
#         enable-AzPSSession: true
    - run: |
        # cp -R /Users/balaga-gayatri/actions-runner /Users/balaga-gayatri/action-runner-copy-ps 
        # sleep 420
        az vm list
